### ISSUE TITLE
Reserve button not visible on cart drawer

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Tara-Henderson-Speed-work--28-May2022#2]
Bug - Reserve button not visible on cart drawer.
Exp - Reserve button should be visible on cart drawer.
Ref Link - https://drive.google.com/file/d/1SNiUDu_u-3e4F_YYnSGdhNsJNvBRQJp1/view

**Comment by devabulabbas** [comment]
I was told to remove that button

**Comment by ankitcedcoss** [comment]
Closing on Not Required
