### ISSUE TITLE
Product not loading on search page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Tara-Henderson-Speed-work--28-May2022#3]
Bug - Product not showing on search page.
Exp - If user search any product and click on see results button then product should be visible on search page.
Ref Link - https://drive.google.com/file/d/112FB4EXUo9zPQZeHkccdvGA22XyxmzGV/view

**Comment by devabulabbas** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
